# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: social_network.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14social_network.proto\x12\x0esocial_network\"k\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\r\n\x05likes\x18\x04 \x01(\x05\x12)\n\x08\x63omments\x18\x05 \x03(\x0b\x32\x17.social_network.Comment\"(\n\x07\x43omment\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"2\n\x11\x43reatePostRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"8\n\x12\x43reatePostResponse\x12\"\n\x04post\x18\x01 \x01(\x0b\x32\x14.social_network.Post\"\x1e\n\x0eGetFeedRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\"6\n\x0fGetFeedResponse\x12#\n\x05posts\x18\x01 \x03(\x0b\x32\x14.social_network.Post\"0\n\x0fLikePostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\"6\n\x10LikePostResponse\x12\"\n\x04post\x18\x01 \x01(\x0b\x32\x14.social_network.Post\"D\n\x12\x43ommentPostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"9\n\x13\x43ommentPostResponse\x12\"\n\x04post\x18\x01 \x01(\x0b\x32\x14.social_network.Post2\xd7\x02\n\rSocialNetwork\x12S\n\nCreatePost\x12!.social_network.CreatePostRequest\x1a\".social_network.CreatePostResponse\x12J\n\x07GetFeed\x12\x1e.social_network.GetFeedRequest\x1a\x1f.social_network.GetFeedResponse\x12M\n\x08LikePost\x12\x1f.social_network.LikePostRequest\x1a .social_network.LikePostResponse\x12V\n\x0b\x43ommentPost\x12\".social_network.CommentPostRequest\x1a#.social_network.CommentPostResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'social_network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POST']._serialized_start=40
  _globals['_POST']._serialized_end=147
  _globals['_COMMENT']._serialized_start=149
  _globals['_COMMENT']._serialized_end=189
  _globals['_CREATEPOSTREQUEST']._serialized_start=191
  _globals['_CREATEPOSTREQUEST']._serialized_end=241
  _globals['_CREATEPOSTRESPONSE']._serialized_start=243
  _globals['_CREATEPOSTRESPONSE']._serialized_end=299
  _globals['_GETFEEDREQUEST']._serialized_start=301
  _globals['_GETFEEDREQUEST']._serialized_end=331
  _globals['_GETFEEDRESPONSE']._serialized_start=333
  _globals['_GETFEEDRESPONSE']._serialized_end=387
  _globals['_LIKEPOSTREQUEST']._serialized_start=389
  _globals['_LIKEPOSTREQUEST']._serialized_end=437
  _globals['_LIKEPOSTRESPONSE']._serialized_start=439
  _globals['_LIKEPOSTRESPONSE']._serialized_end=493
  _globals['_COMMENTPOSTREQUEST']._serialized_start=495
  _globals['_COMMENTPOSTREQUEST']._serialized_end=563
  _globals['_COMMENTPOSTRESPONSE']._serialized_start=565
  _globals['_COMMENTPOSTRESPONSE']._serialized_end=622
  _globals['_SOCIALNETWORK']._serialized_start=625
  _globals['_SOCIALNETWORK']._serialized_end=968
# @@protoc_insertion_point(module_scope)
